version: '3.8'

# Production override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  mongodb:
    volumes:
      - /var/lib/multimodel/mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    volumes:
      - /var/lib/multimodel/redis:/data
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  app:
    volumes:
      - /var/lib/multimodel/uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

